# PostgreSQL setting user
  - become_user: postgres
    become: yes
    shell: rm -rf /usr/local/pgsql/9.3/data
  - become_user: postgres
    become: yes
    shell: mkdir -pm 700 /usr/local/pgsql/9.3/data
  - become_user: postgres
    become: yes
    shell: /usr/pgsql-9.3/bin/initdb --encoding=UTF8 --no-locale --pgdata=/usr/local/pgsql/9.3/data --auth=ident
  - become_user: postgres
    become: yes
    shell: /usr/pgsql-9.3/bin/pg_ctl -D /usr/local/pgsql/9.3/data -l logfile start
  - name: SLEEP
    shell: sleep 10
  - become_user: postgres
    become: yes
    shell: psql -c "alter user postgres with password ''"
  - become_user: postgres
    become: yes
    shell: psql -c "create role root login createdb password ''"
  - become_user: postgres
    become: yes
    shell: /usr/pgsql-9.3/bin/pg_ctl -D /usr/local/pgsql/9.3/data -l logfile stop
