folder_name: 'script'

file_list:
  - file_name: 'create_table.sql'
    url: 'https://github.com/multi-service-fabric/element-manager/raw/master/script/create_table.sql'
  - file_name: 'delete_data.sql'
    url: 'https://github.com/multi-service-fabric/element-manager/raw/master/script/delete_data.sql'
  - file_name: 'drop_table.sql'
    url: 'https://github.com/multi-service-fabric/element-manager/raw/master/script/drop_table.sql'
