# Before installing
  - name: get target dir name
    local_action: command basename {{ rpm_path }}
    register: target
  - name: archive
    local_action: command tar cvf {{ rpm_path }}.tar -C {{ rpm_path }}/../ {{ target.stdout }}

