# Getting em conf
  - name: wget conf
    shell: wget --no-check-certificate --no-cookies {{ item.url }} -O {{ em_path }}/{{ folder_name_conf }}/{{ item.file_name }}
    with_items:
      - "{{ files_conf }}"



    
