# Getting em
  - name: wget src
    shell: wget --no-check-certificate --no-cookies {{ item.url }} -O {{ rpm_path }}/{{ item.file_name }}
    with_items:
      - "{{ files_em }}"
    when: download_flag
  - shell: tar xvfz {{ rpm_path }}/master.tar.gz -C {{ rpm_path }}
    when: download_flag
  - shell: cp -r {{ rpm_path }}/element-manager-master/lib {{ em_path }}
    when: download_flag
  - name: copy src
    shell: cp -r {{ installing_em_path }}/lib {{ em_path }}
    when: download_flag == false
