- hosts: EM
  become: true
  vars_files:
    - vars/{{group_names[1]}}.yml
  roles:
    - before
    - firewall
    - { role: pacemaker, when: "ha_flag"}
    - python
    - ntp
    - sar
    - flask
    - bc
    - em
    - { role: ra-em, when: "ha_flag"}
    - em-postgre

- hosts: DB
  become: true 
  vars_files:
    - vars/{{group_names[1]}}.yml
  roles:
    - before
    - { role: postgre, when: "install_flag"}
    - { role: pacemaker, when: "ha_flag"}
    - db-em
    - firewall


